### ISSUE TITLE
Move header files into a subfolder

### ISSUE THREAD

**Issue by chausner** [xhawk18/promise-cpp#13]
I'd like to include this library in the vcpkg package catalog (https://github.com/microsoft/vcpkg/pull/20340) but ran into an issue that would be nice to get addressed here in the library instead of having to be patched on the vcpkg side.

Currently, the library puts all its header files directly under `include`. This could be problematic because there may be clashes with other libraries that use the same names for their include files, especially since some of the headers use generic names like `add_ons.hpp`.

I suggest to put all headers into a subfolder `promise-cpp` or similar, and refer to them via `#include "promise-cpp/...hpp"` in all files.

**Comment by xhawk18** [comment]
Good idea! I'll change the code in this way soon

**Comment by xhawk18** [comment]
https://github.com/xhawk18/promise-cpp/releases/tag/2.1.2

**Comment by chausner** [comment]
> https://github.com/xhawk18/promise-cpp/releases/tag/2.1.2

Awesome, thanks for the quick action!
